# Generated by Django 5.0.2 on 2025-05-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_like_unique_together_like_unique_appversion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='posts_like',
        ),
    ]
